
[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"

[scrolling]
history = 10000
multiplier = 3

[window]
startup_mode = "Maximized"

[window.padding]
x = 10
y = 10

[cursor]
style = "Underline"

[font]
size = 13.5

normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"

builtin_box_drawing = true

[general]
import = [
  "/usr/lib/node_modules/alacritty-themes/themes/Tokyonight_Night.toml"
]
